### ISSUE TITLE
Error generating adversarial sample

### ISSUE THREAD

**Issue by mrwhu** [DependableSystemsLab/Jujutsu#2]
Thank you so much for such an excellent job. But when I run your program (2. Generate adversarial samples using the adversarial patch and derive their saliency maps) and set --test_size 5000 as you instructed to generate an adversarial sample. But only 3,500 adversarial samples were generated. Is there something wrong with this, or is your program just the way it is.

**Comment by zgkzgk** [comment]
最近在学习对抗补丁的知识，生成补丁的代码中设置了阈值，即当尝试多少次后就跳过，应该是这个原因导致的生成补丁数量小于设置的补丁数量。可以通过增大阈值的方式解决此问题，希望对你有所帮助。
